FROM theiacloud/theia-cloud-operator:0.8.0.MS1

# Copy the customised templates into the /templates/ directory
COPY custom-operator/templateDeployment.yaml /templates/
COPY custom-operator/templateDeploymentWithoutOAuthProxy.yaml /templates/