FROM theiacloud/theia-cloud-operator:0.8.0.MS1

# Copy the customised templates into the /templates/ directory
COPY demo/dockerfiles/demo-operator-custom-template/templateDeployment.yaml /templates/
COPY demo/dockerfiles/demo-operator-custom-template/templateDeploymentWithoutOAuthProxy.yaml /templates/