apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-api-access
rules:
  -
    apiGroups:
      - ""
      - apiextensions.k8s.io
      - theia.cloud
      - networking.k8s.io
      - apps
    resources:
      - customresourcedefinitions
      - appdefinitions
      - ingresses
      - sessions
      - persistentvolumes
      - persistentvolumeclaims
      - services
      - configmaps
      - deployments
    verbs: ["list", "create", "watch", "get", "patch", "delete"]