apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-api-access
rules:
  -
    apiGroups:
      - ""
      - theia.cloud
    resources:
      - sessions
    verbs: ["get", "create", "watch", "delete"]